language: cpp
compiler:
  - gcc
  - clang
before_install:
  - sudo apt-get update -qq
install:
  - sudo apt-get install -qq libcurl4-openssl-dev libboost-thread1.48-dev
script:
  - cmake . && make -j4 && make test ARGS=-j4
after_failure:
  - cat test_server.log
  - tests/run_test_server
  - for t in tests/test_*.cc; do "${t%.cc}"; done
  - tests/stop_test_server
