language: cpp
compiler:
  - gcc
  - clang
install:
  - sudo apt-get update -qq
  - sudo apt-get install -qq libcurl4-openssl-dev
  - sudo apt-get install -qq libboost-dev
script:
  - cmake .
  - make
  - make test
