language: cpp
compiler:
  - gcc
  - clang
before_install:
  - sudo add-apt-repository -y ppa:jaywink/curldebian
  - sudo add-apt-repository -y ppa:kalakris/cmake
  - sudo apt-get update -qq
install:
  - sudo apt-get install -qq libcurl4-openssl-dev libboost-thread1.48-dev cmake
script:
  - cmake . -DUSE_BOOST_TSS=ON && make -j4 && make test ARGS=-j4
after_failure:
  - cat test_server.log
  - tests/run_test_server
  - for t in tests/test_*.cc; do "${t%.cc}"; done
  - tests/stop_test_server
