language: cpp
compiler:
  - gcc
  - clang
install:
  - sudo apt-get update -qq
  - sudo apt-get install -qq libcurl4-openssl-dev libboost-dev
before_script:
  - cmake .
script:
  - make
  - make test
after_failure:
  - cat test_server.log
  - tests/run_test_server
  - find tests -name 'test_*' -perm -u=x | while read t; do "$t"; done
  - tests/stop_test_server
